version: '2'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=tester
    ports:
      - 9306:3306
